services:
  limitit-db:
    image: arm64v8/mysql:8.0
    container_name: limitit-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: limititdb
      MYSQL_USER: limitituser
      MYSQL_PASSWORD: limititpass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - limitit-network
    volumes:
      - mysql_data:/var/lib/mysql

  limitit-redis:
    image: redis:7.0
    container_name: limitit-redis
    ports:
      - "6379:6379"
    networks:
      - limitit-network

  limitit-app:
    build: .
    container_name: limitit-app
    ports:
      - "8080:8080"
    depends_on:
      limitit-db:
        condition: service_healthy
      limitit-redis:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - limitit-network

networks:
  limitit-network:

volumes:
  mysql_data:
